//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperation.Areas.Admin.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyEntityContext : DbContext
    {
        public MyEntityContext()
            : base("name=MyEntityContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Emp> tbl_Emp { get; set; }
        public virtual DbSet<tbl_Employ> tbl_Employ { get; set; }
        public virtual DbSet<tbl_CourseInfo> tbl_CourseInfo { get; set; }
        public virtual DbSet<tbl_Student> tbl_Student { get; set; }
    }
}
